<a href="https://colab.research.google.com/github/Rahmamouradsayed/Credit-Scoring-Model/blob/main/Task_1_codeAlpha.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report , confusion_matrix ,accuracy_score
from sklearn.linear_model import LogisticRegression

In [ ]:
#load data_set
data =pd.read_csv('Credit_Card_dataset.csv')

In [ ]:
data.shape

(101658, 18)

In [ ]:
data.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0

In [ ]:
dataset = data.drop('ID', axis=1)

In [ ]:
# to check from Null Values
dataset.isna().sum()

CODE_GENDER                0
FLAG_OWN_CAR               0
FLAG_OWN_REALTY            0
CNT_CHILDREN               0
AMT_INCOME_TOTAL           0
NAME_INCOME_TYPE           0
NAME_EDUCATION_TYPE        0
NAME_FAMILY_STATUS         0
NAME_HOUSING_TYPE          0
DAYS_BIRTH                 0
DAYS_EMPLOYED              0
FLAG_MOBIL                 0
FLAG_WORK_PHONE            0
FLAG_PHONE                 0
FLAG_EMAIL                 0
OCCUPATION_TYPE        31948
CNT_FAM_MEMBERS            1
dtype: int64

In [ ]:
# Fill missing values in the dataset using backward fill
dataset=dataset.fillna(method='bfill')

In [ ]:
#check all null values are removed after replace null values with backward fill
dataset.isna().sum()

CODE_GENDER            0
FLAG_OWN_CAR           0
FLAG_OWN_REALTY        0
CNT_CHILDREN           0
AMT_INCOME_TOTAL       0
NAME_INCOME_TYPE       0
NAME_EDUCATION_TYPE    0
NAME_FAMILY_STATUS     0
NAME_HOUSING_TYPE      0
DAYS_BIRTH             0
DAYS_EMPLOYED          0
FLAG_MOBIL             0
FLAG_WORK_PHONE        0
FLAG_PHONE             0
FLAG_EMAIL             0
OCCUPATION_TYPE        0
CNT_FAM_MEMBERS        1
dtype: int64

In [ ]:
data.describe()

,ID,CNT_CHILDREN,AMT_INCOME_TOTAL,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS
count,1.016580e+05,101658.000000,1.016580e+05,101658.000000,101658.000000,101658.0,101658.000000,101658.000000,101658.000000,101657.000000
mean,5.367005e+06,0.434073,1.858836e+05,-16066.993803,63155.300449,1.0,0.216451,0.300271,0.086545,2.203567
std,4.043016e+05,0.739729,1.046114e+05,4204.728138,141002.279846,0.0,0.411827,0.458378,0.281169,0.909860
min,5.008804e+06,0.000000,2.700000e+04,-25201.000000,-16365.000000,1.0,0.000000,0.000000,0.000000,1.000000
25%,5.111090e+06,0.000000,1.192500e+05,-19575.000000,-3109.000000,1.0,0.000000,0.000000,0.000000,2.000000
50%,5.237228e+06,0.000000,1.575000e+05,-15624.000000,-1493.000000,1.0,0.000000,0.000000,0.000000,2.000000
75%,5.401606e+06,1.000000,2.250000e+05,-12564.000000,-357.000000,1.0,0.000000,1.000000,0.000000,3.000000
max,6.840301e+06,19.000000,3.825000e+06,-7489.000000,365243.000000,1.0,1.000000,1.000000,1.000000,20.000000

In [ ]:
dataset.shape

(101658, 17)

In [ ]:
label_encoder = LabelEncoder()

dataset['CODE_GENDER']=label_encoder.fit_transform(dataset['CODE_GENDER'])
dataset['FLAG_OWN_CAR']=label_encoder.fit_transform(dataset['FLAG_OWN_CAR'])
dataset['FLAG_OWN_REALTY']=label_encoder.fit_transform(dataset['FLAG_OWN_REALTY'])
dataset['NAME_INCOME_TYPE'] = label_encoder.fit_transform(dataset['NAME_INCOME_TYPE'])
dataset['NAME_EDUCATION_TYPE'] = label_encoder.fit_transform(dataset['NAME_EDUCATION_TYPE'])
dataset['NAME_FAMILY_STATUS'] = label_encoder.fit_transform(dataset['NAME_FAMILY_STATUS'])
dataset['NAME_HOUSING_TYPE'] = label_encoder.fit_transform(dataset['NAME_HOUSING_TYPE'])
dataset['OCCUPATION_TYPE'] = label_encoder.fit_transform(dataset['OCCUPATION_TYPE'])

In [ ]:
dataset

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
0,1,1,1,0,427500.0,4,1,0,4,-12005,-4542,1,1,0,0,17,2.0
1,1,1,1,0,427500.0,4,1,0,4,-12005,-4542,1,1,0,0,17,2.0
2,1,1,1,0,112500.0,4,4,1,1,-21474,-1134,1,0,0,0,17,2.0
3,0,0,1,0,270000.0,0,4,3,1,-19110,-3051,1,0,1,1,15,1.0
4,0,0,1,0,270000.0,0,4,3,1,-19110,-3051,1,0,1,1,15,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101653,1,1,1,0,225000.0,4,4,3,1,-12588,-1003,1,1,0,0,4,1.0
101654,1,1,1,0,225000.0,4,4,3,1,-12588,-1003,1,1,0,0,4,1.0
101655,1,1,1,0,225000.0,4,4,3,1,-12588,-1003,1,1,0,0,4,1.0
101656,0,0,1,0,270000.0,4,4,2,1,-20516,-2830,1,0,1,0,9,1.0
101657,0,0,1,0,270000.0,4,4,2,1,-20516,-2830,1,0,1,0,8,NaN

In [ ]:
# Extract the target variable (Y) from the dataset
Y=dataset.iloc[:,0].values

# Extract the feature variables (X) from the dataset
X=dataset.iloc[:, 1:16].values

In [ ]:
# Split the data into training and testing sets
X_train ,X_test , Y_train , Y_test=train_test_split(X,Y , test_size=0.2,random_state=0,stratify=Y)

In [ ]:
# Create an instance of StandardScaler
scaler = StandardScaler()

In [ ]:
# Standardize the feature variables in the training set
X_train = scaler.fit_transform(X_train)

In [ ]:
# Standardize the feature variables in the testing set
X_test = scaler.transform(X_test)

In [ ]:
# Create an instance of the LogisticRegression classifier
classifier=LogisticRegression()

In [ ]:
# Fit the classifier to the training data
classifier.fit(X_train,Y_train)

LogisticRegression()

In [ ]:
# Make predictions on the testing set
y_pred = classifier.predict(X_test)

In [ ]:
print(confusion_matrix(Y_test,y_pred))

[[11854  1940]
 [ 3479  3059]]

In [ ]:
print(accuracy_score(Y_test, y_pred))

0.7334743261853236

In [ ]:
predictions = classifier.predict_proba(X_test)
predictions

array([[0.7319285 , 0.2680715 ],
       [0.79753064, 0.20246936],
       [0.44261059, 0.55738941],
       ...,
       [0.69861067, 0.30138933],
       [0.43570226, 0.56429774],
       [0.67750225, 0.32249775]])

In [ ]:
df_prediction_prob = pd.DataFrame(predictions, columns = ['prob_0', 'prob_1'])
df_prediction_target = pd.DataFrame(classifier.predict(X_test), columns = ['predicted_TARGET'])
df_test_dataset = pd.DataFrame(Y_test,columns= ['Actual Outcome'])

dfx=pd.concat([df_test_dataset, df_prediction_prob, df_prediction_target], axis=1)

dfx.to_csv("Credit_Card_dataset.csv", sep=',', encoding='UTF-8')

dfx.head()

   Actual Outcome    prob_0    prob_1  predicted_TARGET
0               1  0.731929  0.268071                 0
1               0  0.797531  0.202469                 0
2               0  0.442611  0.557389                 1
3               1  0.416095  0.583905                 1
4               0  0.854630  0.145370                 0